### ISSUE TITLE
First Certificate Error

### ISSUE THREAD

**Issue by mrbryce2000** [learnweb/moodle-fileconverter_onlyoffice#6]
I see the following error in /var/log/onlyoffice/documentserver/converter
[2020-04-17T09:42:19.874] [ERROR] nodeJS - error downloadFile:url=https://moodle.legacyknights.org/pluginfile.php/1/fileconverter_onlyoffice/ori$
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)

The grading preview in Moodle failes with a "PDF is corrupt" error.

Both servers are local with a split DNS. So the URL above points to the local server IP onsite. I setup OnlyOffice on an Ubuntu Server 16.04 VM.

**Comment by Dagefoerde** [comment]
When you are using https, you need to make sure that the TLS certificate is valid (for the used domain) and that it is verifiable by the server software. That means, a self-signed certificate won't work, unless you know how to make it known to the verifying software. As far as I know, this is not possible in PHP, but might be possible in the stack used by ONLYOFFICE - but I don't know about that.

**Comment by mrbryce2000** [comment]
Thank you for your reply. I am using a LetsEncrypt cert on both my Moodle and OnlyOffice servers. I followed the instructions on setting up HTTPS for OnlyOffice, and used the LetsEncrypt paths for the ds.conf.

**Comment by Dagefoerde** [comment]
Sorry, I really can't help with this as this is not a plugin issue, but a server certificate configuration issue. As I stated, there is no workaround in PHP to skip validation (which is not recommended anyway). I cannot see your certificate, but admittedly I have little to none experience with LetsEncrypt anyway. I would like to encourage you to ask someone knowledgeable with LetsEncrypt certificates to fix this!
